name: Deploy InVoice-Genrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 120s

          script: |
            set -e

            cd /root/invoice-generator

            echo "Updating repository..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing frontend dependencies..."
            cd client
            npm install

            echo "Building frontend..."
            npm run build

            echo "Installing backend dependencies..."
            cd ../server
            npm install

            echo "Restarting frontend..."
            pm2 restart invoice-frontend

            echo "Restarting backend..."
            pm2 restart invoice-backend

            echo "Saving PM2..."
            pm2 save

            echo "✅ Deployment completed successfully."
